spring.application.name=profelaapp

spring.datasource.url=jdbc:mysql://mysql-profelaapp-emilio-profelaapp.l.aivencloud.com:28032/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_9TNjhVA4NJ3wip0xl4o
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver